domain: []
external_id_method: row_get_id
external_id_nomenclature: product_pricelist_%s
fields:
  show_products:
    from:
      name: show_products
      type: boolean
    map_method: magic_map
    to:
      name: show_products
      type: boolean
model_from: product.pricelist
model_to: product.pricelist
no_match_fields:
  price:
    from:
      name: price
      type: monetary
