domain: []
external_id_method: row_get_id
external_id_nomenclature: product_template_%s
fields:
  service_to_purchase:
    from:
      name: service_to_purchase
      type: boolean
    map_method: magic_map
    to:
      name: service_to_purchase
      type: boolean
model_from: product.template
model_to: product.template
no_match_fields: []
