domain: []
external_id_method: row_get_id
external_id_nomenclature: product_category_%s
fields:
  putaway_rule_ids:
    from:
      name: putaway_rule_ids
      relation: stock.putaway.rule
      relation_field: category_id
      type: one2many
    map_method: magic_map
    to:
      name: putaway_rule_ids
      relation: stock.putaway.rule
      relation_field: category_id
      type: one2many
  removal_strategy_id:
    from:
      name: removal_strategy_id
      relation: product.removal
      type: many2one
    map_method: magic_map
    to:
      name: removal_strategy_id
      relation: product.removal
      type: many2one
  route_ids:
    from:
      name: route_ids
      relation: stock.location.route
      type: many2many
    map_method: magic_map
    to:
      name: route_ids
      relation: stock.location.route
      type: many2many
model_from: product.category
model_to: product.category
no_match_fields:
  total_route_ids:
    from:
      name: total_route_ids
      relation: stock.location.route
      type: many2many
