domain: []
external_id_method: row_get_id
external_id_nomenclature: product_category_%s
fields:
  property_account_expense_categ_id:
    from:
      name: property_account_expense_categ_id
      relation: account.account
      type: many2one
    map_method: magic_map
    to:
      name: property_account_expense_categ_id
      relation: account.account
      type: many2one
  property_account_income_categ_id:
    from:
      name: property_account_income_categ_id
      relation: account.account
      type: many2one
    map_method: magic_map
    to:
      name: property_account_income_categ_id
      relation: account.account
      type: many2one
model_from: product.category
model_to: product.category
no_match_fields: []
