domain: []
external_id_method: row_get_id
external_id_nomenclature: product_product_%s
fields:
  property_account_expense_id:
    from:
      name: property_account_expense_id
      relation: account.account
      type: many2one
    map_method: magic_map
    to:
      name: property_account_expense_id
      relation: account.account
      type: many2one
  property_account_income_id:
    from:
      name: property_account_income_id
      relation: account.account
      type: many2one
    map_method: magic_map
    to:
      name: property_account_income_id
      relation: account.account
      type: many2one
  supplier_taxes_id:
    from:
      name: supplier_taxes_id
      relation: account.tax
      type: many2many
    map_method: magic_map
    to:
      name: supplier_taxes_id
      relation: account.tax
      type: many2many
  taxes_id:
    from:
      name: taxes_id
      relation: account.tax
      type: many2many
    map_method: magic_map
    to:
      name: taxes_id
      relation: account.tax
      type: many2many
model_from: product.product
model_to: product.product
no_match_fields: []
