domain: []
external_id_method: row_get_id
external_id_nomenclature: product_product_%s
fields:
  route_ids:
    from:
      name: route_ids
      relation: stock.location.route
      type: many2many
    map_method: magic_map
    to:
      name: route_ids
      relation: stock.location.route
      type: many2many
model_from: product.product
model_to: product.product
no_match_fields: []
