domain: []
external_id_method: row_get_id
external_id_nomenclature: product_category_%s
fields:
  property_cost_method:
    from:
      name: property_cost_method
      type: selection
    map_method: magic_map
    to:
      name: property_cost_method
      type: selection
  property_stock_account_input_categ_id:
    from:
      name: property_stock_account_input_categ_id
      relation: account.account
      type: many2one
    map_method: magic_map
    to:
      name: property_stock_account_input_categ_id
      relation: account.account
      type: many2one
  property_stock_account_output_categ_id:
    from:
      name: property_stock_account_output_categ_id
      relation: account.account
      type: many2one
    map_method: magic_map
    to:
      name: property_stock_account_output_categ_id
      relation: account.account
      type: many2one
  property_stock_journal:
    from:
      name: property_stock_journal
      relation: account.journal
      type: many2one
    map_method: magic_map
    to:
      name: property_stock_journal
      relation: account.journal
      type: many2one
  property_stock_valuation_account_id:
    from:
      name: property_stock_valuation_account_id
      relation: account.account
      type: many2one
    map_method: magic_map
    to:
      name: property_stock_valuation_account_id
      relation: account.account
      type: many2one
  property_valuation:
    from:
      name: property_valuation
      type: selection
    map_method: magic_map
    to:
      name: property_valuation
      type: selection
model_from: product.category
model_to: product.category
no_match_fields: []
