domain: []
external_id_method: row_get_id
external_id_nomenclature: product_product_%s
fields:
  stock_valuation_layer_ids:
    from:
      name: stock_valuation_layer_ids
      relation: stock.valuation.layer
      relation_field: product_id
      type: one2many
    map_method: magic_map
    to:
      name: stock_valuation_layer_ids
      relation: stock.valuation.layer
      relation_field: product_id
      type: one2many
model_from: product.product
model_to: product.product
no_match_fields:
  cost_method:
    from:
      name: cost_method
      type: selection
  quantity_svl:
    from:
      name: quantity_svl
      type: float
  valuation:
    from:
      name: valuation
      type: selection
  value_svl:
    from:
      name: value_svl
      type: float
