domain: []
external_id_method: row_get_id
external_id_nomenclature: product_product_%s
fields:
  available_in_pos:
    from:
      name: available_in_pos
      type: boolean
    map_method: magic_map
    to:
      name: available_in_pos
      type: boolean
  pos_categ_id:
    from:
      name: pos_categ_id
      relation: pos.category
      type: many2one
    map_method: magic_map
    to:
      name: pos_categ_id
      relation: pos.category
      type: many2one
  to_weight:
    from:
      name: to_weight
      type: boolean
    map_method: magic_map
    to:
      name: to_weight
      type: boolean
model_from: product.product
model_to: product.product
no_match_fields: []
