domain: []
external_id_method: row_get_id
external_id_nomenclature: product_category_%s
fields:
  child_id:
    from:
      name: child_id
      relation: product.category
      relation_field: parent_id
      type: one2many
    map_method: magic_map
    to:
      name: child_id
      relation: product.category
      relation_field: parent_id
      type: one2many
  name:
    from:
      name: name
      type: char
    map_method: magic_map
    to:
      name: name
      type: char
  parent_id:
    from:
      name: parent_id
      relation: product.category
      type: many2one
    map_method: magic_map
    to:
      name: parent_id
      relation: product.category
      type: many2one
  parent_path:
    from:
      name: parent_path
      type: char
    map_method: magic_map
    to:
      name: parent_path
      type: char
model_from: product.category
model_to: product.category
no_match_fields:
  complete_name:
    from:
      name: complete_name
      type: char
  display_name:
    from:
      name: display_name
      type: char
  product_count:
    from:
      name: product_count
      type: integer
